### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sffr-dev** [Alex-U13/landing_step1#1]
1. https://github.com/Alex-U13/landing_step1/blob/06df15274c1d8ced4cfde6e5c036cfe57096867c/index.html#L43-L45
https://github.com/Alex-U13/landing_step1/blob/06df15274c1d8ced4cfde6e5c036cfe57096867c/index.html#L59-L64
Не нужно оборачивать каждую кнопку в форму. Форма нужна, если есть инпуты, из которых нужно собрать информацию, введенную пользователем.

2. https://github.com/Alex-U13/landing_step1/blob/06df15274c1d8ced4cfde6e5c036cfe57096867c/css/styles.css#L984
https://github.com/Alex-U13/landing_step1/blob/06df15274c1d8ced4cfde6e5c036cfe57096867c/css/styles.css#L947
Вот эти стили создают белую полосу. Нужно ограничить максимальную ширину, а обычную сделать 100%

3. https://github.com/Alex-U13/landing_step1/blob/06df15274c1d8ced4cfde6e5c036cfe57096867c/css/styles.css#L396
Ошибка

4. Все чекбоксы должны иметь один класс и работать одинаково. Если нужно изменить размер или цвет шрифта - используйте модификаторы

5. https://github.com/Alex-U13/landing_step1/blob/06df15274c1d8ced4cfde6e5c036cfe57096867c/css/styles.css#L293
Из-за этого стиля лейблы встают по центру. Нужно переопределить его в родительском элементе.

6. Чтобы поменять местами кнопку и чекбокс - используйте свойство `order`

**Comment by Alex-U13** [comment]
У меня стоит один и тот же класс с немудренным названием "checkbox-class" ... В общем я не понимаю как сделать правильно

> 4\. Все чекбоксы должны иметь один класс и работать одинаково. Если нужно изменить размер или цвет шрифта - используйте модификаторы

**Comment by sffr-dev** [comment]
https://github.com/Alex-U13/landing_step1/blob/c5b9950085a91c1009b57df43b2b464429e69730/index.html#L245
https://github.com/Alex-U13/landing_step1/blob/c5b9950085a91c1009b57df43b2b464429e69730/index.html#L375
`type="checkbox"` без пробела.

https://github.com/Alex-U13/landing_step1/blob/c5b9950085a91c1009b57df43b2b464429e69730/css/styles.css#L840
Вот это уберите тоже и огромный паддинг вот тут
https://github.com/Alex-U13/landing_step1/blob/c5b9950085a91c1009b57df43b2b464429e69730/css/styles.css#L932

**Comment by Alex-U13** [comment]
Спасибо
